name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: markdown syntax
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
